import Sort;
import arrayGenerator;

class Main{
    public static void main(String[] args) throws InterruptedException {

        Sort sort = new Sort();
        ArrayGenerator arrayGenerator = new ArrayGenerator();

        // Testing selection, insertion, merge and shell sort for array size: 2^7 - 2^15.
        long startTime = System.nanoTime();
        int randseloper17 = sort.selectionSort(arrayGenerator.generateRandomArray(128));
        int randseloper27 = sort.selectionSort(arrayGenerator.generateRandomArray(128));
        int randseloper37 = sort.selectionSort(arrayGenerator.generateRandomArray(128));
        int randseloper47 = sort.selectionSort(arrayGenerator.generateRandomArray(128));
        int randseloper57 = sort.selectionSort(arrayGenerator.generateRandomArray(128));
        long stopTime = System.nanoTime();
        int randseloper7 = (int)((double)(randseloper17+randseloper27+randseloper37+randseloper47+randseloper57)/5);
        long randseltime7 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupseloper7 = sort.selectionSort(arrayGenerator.generateSortedToUp(128));
        stopTime = System.nanoTime();
        long toupseltime7 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownseloper7 = sort.selectionSort(arrayGenerator.generateSortedToDown(128));
        stopTime = System.nanoTime();
        long todownseltime7 = stopTime - startTime;
        startTime = System.nanoTime();
        int simseloper17 = sort.selectionSort(arrayGenerator.generateSimpleArray(128));
        int simseloper27 = sort.selectionSort(arrayGenerator.generateSimpleArray(128));
        int simseloper37 = sort.selectionSort(arrayGenerator.generateSimpleArray(128));
        stopTime = System.nanoTime();
        int simseloper7 = (int)((simseloper17+simseloper27+simseloper37) / 5);
        long simseltime7 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randinsoper17 = sort.insertionSort(arrayGenerator.generateRandomArray(128));
        int randinsoper27 = sort.insertionSort(arrayGenerator.generateRandomArray(128));
        int randinsoper37 = sort.insertionSort(arrayGenerator.generateRandomArray(128));
        int randinsoper47 = sort.insertionSort(arrayGenerator.generateRandomArray(128));
        int randinsoper57 = sort.insertionSort(arrayGenerator.generateRandomArray(128));
        stopTime = System.nanoTime();
        int randinsoper7 = (int)((double)(randinsoper17+randinsoper27+randinsoper37+randinsoper47+randinsoper57)/5);
        long randinstime7 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupinsoper7 = sort.insertionSort(arrayGenerator.generateSortedToUp(128));
        stopTime = System.nanoTime();
        long toupinstime7 = stopTime - startTime;
        startTime = System.nanoTime();
        int todowninsoper7 = sort.insertionSort(arrayGenerator.generateSortedToDown(128));
        stopTime = System.nanoTime();
        long todowninstime7 = stopTime - startTime;
        startTime = System.nanoTime();
        int siminsoper17 = sort.insertionSort(arrayGenerator.generateSimpleArray(128));
        int siminsoper27 = sort.insertionSort(arrayGenerator.generateSimpleArray(128));
        int siminsoper37 = sort.insertionSort(arrayGenerator.generateSimpleArray(128));
        stopTime = System.nanoTime();
        int siminsoper7 = (int)((siminsoper17+siminsoper27+siminsoper37) / 5);
        long siminstime7 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randmrgoper17 = sort.mergeSort(arrayGenerator.generateRandomArray(128));
        int randmrgoper27 = sort.mergeSort(arrayGenerator.generateRandomArray(128));
        int randmrgoper37 = sort.mergeSort(arrayGenerator.generateRandomArray(128));
        int randmrgoper47 = sort.mergeSort(arrayGenerator.generateRandomArray(128));
        int randmrgoper57 = sort.mergeSort(arrayGenerator.generateRandomArray(128));
        stopTime = System.nanoTime();
        int randmrgoper7 = (int)((double)(randmrgoper17+randmrgoper27+randmrgoper37+randmrgoper47+randmrgoper57)/5);
        long randmrgtime7 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupmrgoper7 = sort.mergeSort(arrayGenerator.generateSortedToUp(128));
        stopTime = System.nanoTime();
        long toupmrgtime7 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownmrgoper7 = sort.mergeSort(arrayGenerator.generateSortedToDown(128));
        stopTime = System.nanoTime();
        long todownmrgtime7 = stopTime - startTime;
        startTime = System.nanoTime();
        int simmrgoper17 = sort.mergeSort(arrayGenerator.generateSimpleArray(128));
        int simmrgoper27 = sort.mergeSort(arrayGenerator.generateSimpleArray(128));
        int simmrgoper37 = sort.mergeSort(arrayGenerator.generateSimpleArray(128));
        stopTime = System.nanoTime();
        int simmrgoper7 = (int)((simmrgoper17+simmrgoper27+simmrgoper37) / 5);
        long simmrgtime7 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randshloper17 = sort.shellSort(arrayGenerator.generateRandomArray(128));
        int randshloper27 = sort.shellSort(arrayGenerator.generateRandomArray(128));
        int randshloper37 = sort.shellSort(arrayGenerator.generateRandomArray(128));
        int randshloper47 = sort.shellSort(arrayGenerator.generateRandomArray(128));
        int randshloper57 = sort.shellSort(arrayGenerator.generateRandomArray(128));
        stopTime = System.nanoTime();
        int randshloper7 = (int)((double)(randshloper17+randshloper27+randshloper37+randshloper47+randshloper57)/5);
        long randshltime7 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupshloper7 = sort.shellSort(arrayGenerator.generateSortedToUp(128));
        stopTime = System.nanoTime();
        long toupshltime7 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownshloper7 = sort.shellSort(arrayGenerator.generateSortedToDown(128));
        stopTime = System.nanoTime();
        long todownshltime7 = stopTime - startTime;
        startTime = System.nanoTime();
        int simshloper17 = sort.shellSort(arrayGenerator.generateSimpleArray(128));
        int simshloper27 = sort.shellSort(arrayGenerator.generateSimpleArray(128));
        int simshloper37 = sort.shellSort(arrayGenerator.generateSimpleArray(128));
        stopTime = System.nanoTime();
        int simshloper7 = (int)((simshloper17+simshloper27+simshloper37) / 5);
        long simshltime7 = (stopTime - startTime) / 3;


        startTime = System.nanoTime();
        int randseloper18 = sort.selectionSort(arrayGenerator.generateRandomArray(256));
        int randseloper28 = sort.selectionSort(arrayGenerator.generateRandomArray(256));
        int randseloper38 = sort.selectionSort(arrayGenerator.generateRandomArray(256));
        int randseloper48 = sort.selectionSort(arrayGenerator.generateRandomArray(256));
        int randseloper58 = sort.selectionSort(arrayGenerator.generateRandomArray(256));
        stopTime = System.nanoTime();
        int randseloper8 = (int)((double)(randseloper18+randseloper28+randseloper38+randseloper48+randseloper58)/5);
        long randseltime8 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupseloper8 = sort.selectionSort(arrayGenerator.generateSortedToUp(256));
        stopTime = System.nanoTime();
        long toupseltime8 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownseloper8 = sort.selectionSort(arrayGenerator.generateSortedToDown(256));
        stopTime = System.nanoTime();
        long todownseltime8 = stopTime - startTime;
        startTime = System.nanoTime();
        int simseloper18 = sort.selectionSort(arrayGenerator.generateSimpleArray(256));
        int simseloper28 = sort.selectionSort(arrayGenerator.generateSimpleArray(256));
        int simseloper38 = sort.selectionSort(arrayGenerator.generateSimpleArray(256));
        stopTime = System.nanoTime();
        int simseloper8 = (int)((simseloper18+simseloper28+simseloper38) / 5);
        long simseltime8 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randinsoper18 = sort.insertionSort(arrayGenerator.generateRandomArray(256));
        int randinsoper28 = sort.insertionSort(arrayGenerator.generateRandomArray(256));
        int randinsoper38 = sort.insertionSort(arrayGenerator.generateRandomArray(256));
        int randinsoper48 = sort.insertionSort(arrayGenerator.generateRandomArray(256));
        int randinsoper58 = sort.insertionSort(arrayGenerator.generateRandomArray(256));
        stopTime = System.nanoTime();
        int randinsoper8 = (int)((double)(randinsoper18+randinsoper28+randinsoper38+randinsoper48+randinsoper58)/5);
        long randinstime8 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupinsoper8 = sort.insertionSort(arrayGenerator.generateSortedToUp(256));
        stopTime = System.nanoTime();
        long toupinstime8 = stopTime - startTime;
        startTime = System.nanoTime();
        int todowninsoper8 = sort.insertionSort(arrayGenerator.generateSortedToDown(256));
        stopTime = System.nanoTime();
        long todowninstime8 = stopTime - startTime;
        startTime = System.nanoTime();
        int siminsoper18 = sort.insertionSort(arrayGenerator.generateSimpleArray(256));
        int siminsoper28 = sort.insertionSort(arrayGenerator.generateSimpleArray(256));
        int siminsoper38 = sort.insertionSort(arrayGenerator.generateSimpleArray(256));
        stopTime = System.nanoTime();
        int siminsoper8 = (int)((siminsoper18+siminsoper28+siminsoper38) / 5);
        long siminstime8 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randmrgoper18 = sort.mergeSort(arrayGenerator.generateRandomArray(256));
        int randmrgoper28 = sort.mergeSort(arrayGenerator.generateRandomArray(256));
        int randmrgoper38 = sort.mergeSort(arrayGenerator.generateRandomArray(256));
        int randmrgoper48 = sort.mergeSort(arrayGenerator.generateRandomArray(256));
        int randmrgoper58 = sort.mergeSort(arrayGenerator.generateRandomArray(256));
        stopTime = System.nanoTime();
        int randmrgoper8 = (int)((double)(randmrgoper18+randmrgoper28+randmrgoper38+randmrgoper48+randmrgoper58)/5);
        long randmrgtime8 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupmrgoper8 = sort.mergeSort(arrayGenerator.generateSortedToUp(256));
        stopTime = System.nanoTime();
        long toupmrgtime8 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownmrgoper8 = sort.mergeSort(arrayGenerator.generateSortedToDown(256));
        stopTime = System.nanoTime();
        long todownmrgtime8 = stopTime - startTime;
        startTime = System.nanoTime();
        int simmrgoper18 = sort.mergeSort(arrayGenerator.generateSimpleArray(256));
        int simmrgoper28 = sort.mergeSort(arrayGenerator.generateSimpleArray(256));
        int simmrgoper38 = sort.mergeSort(arrayGenerator.generateSimpleArray(256));
        stopTime = System.nanoTime();
        int simmrgoper8 = (int)((simmrgoper18+simmrgoper28+simmrgoper38) / 5);
        long simmrgtime8 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randshloper18 = sort.shellSort(arrayGenerator.generateRandomArray(256));
        int randshloper28 = sort.shellSort(arrayGenerator.generateRandomArray(256));
        int randshloper38 = sort.shellSort(arrayGenerator.generateRandomArray(256));
        int randshloper48 = sort.shellSort(arrayGenerator.generateRandomArray(256));
        int randshloper58 = sort.shellSort(arrayGenerator.generateRandomArray(256));
        stopTime = System.nanoTime();
        int randshloper8 = (int)((double)(randshloper18+randshloper28+randshloper38+randshloper48+randshloper58)/5);
        long randshltime8 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupshloper8 = sort.shellSort(arrayGenerator.generateSortedToUp(256));
        stopTime = System.nanoTime();
        long toupshltime8 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownshloper8 = sort.shellSort(arrayGenerator.generateSortedToDown(256));
        stopTime = System.nanoTime();
        long todownshltime8 = stopTime - startTime;
        startTime = System.nanoTime();
        int simshloper18 = sort.shellSort(arrayGenerator.generateSimpleArray(256));
        int simshloper28 = sort.shellSort(arrayGenerator.generateSimpleArray(256));
        int simshloper38 = sort.shellSort(arrayGenerator.generateSimpleArray(256));
        stopTime = System.nanoTime();
        int simshloper8 = (int)((simshloper18+simshloper28+simshloper38) / 5);
        long simshltime8 = (stopTime - startTime) / 3;


        startTime = System.nanoTime();
        int randseloper19 = sort.selectionSort(arrayGenerator.generateRandomArray(512));
        int randseloper29 = sort.selectionSort(arrayGenerator.generateRandomArray(512));
        int randseloper39 = sort.selectionSort(arrayGenerator.generateRandomArray(512));
        int randseloper49 = sort.selectionSort(arrayGenerator.generateRandomArray(512));
        int randseloper59 = sort.selectionSort(arrayGenerator.generateRandomArray(512));
        stopTime = System.nanoTime();
        int randseloper9 = (int)((double)(randseloper19+randseloper29+randseloper39+randseloper49+randseloper59)/5);
        long randseltime9 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupseloper9 = sort.selectionSort(arrayGenerator.generateSortedToUp(512));
        stopTime = System.nanoTime();
        long toupseltime9 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownseloper9 = sort.selectionSort(arrayGenerator.generateSortedToDown(512));
        stopTime = System.nanoTime();
        long todownseltime9 = stopTime - startTime;
        startTime = System.nanoTime();
        int simseloper19 = sort.selectionSort(arrayGenerator.generateSimpleArray(512));
        int simseloper29 = sort.selectionSort(arrayGenerator.generateSimpleArray(512));
        int simseloper39 = sort.selectionSort(arrayGenerator.generateSimpleArray(512));
        stopTime = System.nanoTime();
        int simseloper9 = (int)((simseloper19+simseloper29+simseloper39) / 5);
        long simseltime9 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randinsoper19 = sort.insertionSort(arrayGenerator.generateRandomArray(512));
        int randinsoper29 = sort.insertionSort(arrayGenerator.generateRandomArray(512));
        int randinsoper39 = sort.insertionSort(arrayGenerator.generateRandomArray(512));
        int randinsoper49 = sort.insertionSort(arrayGenerator.generateRandomArray(512));
        int randinsoper59 = sort.insertionSort(arrayGenerator.generateRandomArray(512));
        stopTime = System.nanoTime();
        int randinsoper9 = (int)((double)(randinsoper19+randinsoper29+randinsoper39+randinsoper49+randinsoper59)/5);
        long randinstime9 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupinsoper9 = sort.insertionSort(arrayGenerator.generateSortedToUp(512));
        stopTime = System.nanoTime();
        long toupinstime9 = stopTime - startTime;
        startTime = System.nanoTime();
        int todowninsoper9 = sort.insertionSort(arrayGenerator.generateSortedToDown(512));
        stopTime = System.nanoTime();
        long todowninstime9 = stopTime - startTime;
        startTime = System.nanoTime();
        int siminsoper19 = sort.insertionSort(arrayGenerator.generateSimpleArray(512));
        int siminsoper29 = sort.insertionSort(arrayGenerator.generateSimpleArray(512));
        int siminsoper39 = sort.insertionSort(arrayGenerator.generateSimpleArray(512));
        stopTime = System.nanoTime();
        int siminsoper9 = (int)((siminsoper19+siminsoper29+siminsoper39) / 5);
        long siminstime9 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randmrgoper19 = sort.mergeSort(arrayGenerator.generateRandomArray(512));
        int randmrgoper29 = sort.mergeSort(arrayGenerator.generateRandomArray(512));
        int randmrgoper39 = sort.mergeSort(arrayGenerator.generateRandomArray(512));
        int randmrgoper49 = sort.mergeSort(arrayGenerator.generateRandomArray(512));
        int randmrgoper59 = sort.mergeSort(arrayGenerator.generateRandomArray(512));
        stopTime = System.nanoTime();
        int randmrgoper9 = (int)((double)(randmrgoper19+randmrgoper29+randmrgoper39+randmrgoper49+randmrgoper59)/5);
        long randmrgtime9 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupmrgoper9 = sort.mergeSort(arrayGenerator.generateSortedToUp(512));
        stopTime = System.nanoTime();
        long toupmrgtime9 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownmrgoper9 = sort.mergeSort(arrayGenerator.generateSortedToDown(512));
        stopTime = System.nanoTime();
        long todownmrgtime9 = stopTime - startTime;
        startTime = System.nanoTime();
        int simmrgoper19 = sort.mergeSort(arrayGenerator.generateSimpleArray(512));
        int simmrgoper29 = sort.mergeSort(arrayGenerator.generateSimpleArray(512));
        int simmrgoper39 = sort.mergeSort(arrayGenerator.generateSimpleArray(512));
        stopTime = System.nanoTime();
        int simmrgoper9 = (int)((simmrgoper19+simmrgoper29+simmrgoper39) / 5);
        long simmrgtime9 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randshloper19 = sort.shellSort(arrayGenerator.generateRandomArray(512));
        int randshloper29 = sort.shellSort(arrayGenerator.generateRandomArray(512));
        int randshloper39 = sort.shellSort(arrayGenerator.generateRandomArray(512));
        int randshloper49 = sort.shellSort(arrayGenerator.generateRandomArray(512));
        int randshloper59 = sort.shellSort(arrayGenerator.generateRandomArray(512));
        stopTime = System.nanoTime();
        int randshloper9 = (int)((double)(randshloper19+randshloper29+randshloper39+randshloper49+randshloper59)/5);
        long randshltime9 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupshloper9 = sort.shellSort(arrayGenerator.generateSortedToUp(512));
        stopTime = System.nanoTime();
        long toupshltime9 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownshloper9 = sort.shellSort(arrayGenerator.generateSortedToDown(512));
        stopTime = System.nanoTime();
        long todownshltime9 = stopTime - startTime;
        startTime = System.nanoTime();
        int simshloper19 = sort.shellSort(arrayGenerator.generateSimpleArray(512));
        int simshloper29 = sort.shellSort(arrayGenerator.generateSimpleArray(512));
        int simshloper39 = sort.shellSort(arrayGenerator.generateSimpleArray(512));
        stopTime = System.nanoTime();
        int simshloper9 = (int)((simshloper19+simshloper29+simshloper39) / 5);
        long simshltime9 = (stopTime - startTime) / 3;


        startTime = System.nanoTime();
        int randseloper110 = sort.selectionSort(arrayGenerator.generateRandomArray(1024));
        int randseloper210 = sort.selectionSort(arrayGenerator.generateRandomArray(1024));
        int randseloper310 = sort.selectionSort(arrayGenerator.generateRandomArray(1024));
        int randseloper410 = sort.selectionSort(arrayGenerator.generateRandomArray(1024));
        int randseloper510 = sort.selectionSort(arrayGenerator.generateRandomArray(1024));
        stopTime = System.nanoTime();
        int randseloper10 = (int)((double)(randseloper110+randseloper210+randseloper310+randseloper410+randseloper510)/5);
        long randseltime10 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupseloper10 = sort.selectionSort(arrayGenerator.generateSortedToUp(1024));
        stopTime = System.nanoTime();
        long toupseltime10 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownseloper10 = sort.selectionSort(arrayGenerator.generateSortedToDown(1024));
        stopTime = System.nanoTime();
        long todownseltime10 = stopTime - startTime;
        startTime = System.nanoTime();
        int simseloper110 = sort.selectionSort(arrayGenerator.generateSimpleArray(1024));
        int simseloper210 = sort.selectionSort(arrayGenerator.generateSimpleArray(1024));
        int simseloper310 = sort.selectionSort(arrayGenerator.generateSimpleArray(1024));
        stopTime = System.nanoTime();
        int simseloper10 = (int)((simseloper110+simseloper210+simseloper310) / 5);
        long simseltime10 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randinsoper110 = sort.insertionSort(arrayGenerator.generateRandomArray(1024));
        int randinsoper210 = sort.insertionSort(arrayGenerator.generateRandomArray(1024));
        int randinsoper310 = sort.insertionSort(arrayGenerator.generateRandomArray(1024));
        int randinsoper410 = sort.insertionSort(arrayGenerator.generateRandomArray(1024));
        int randinsoper510 = sort.insertionSort(arrayGenerator.generateRandomArray(1024));
        stopTime = System.nanoTime();
        int randinsoper10 = (int)((double)(randinsoper110+randinsoper210+randinsoper310+randinsoper410+randinsoper510)/5);
        long randinstime10 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupinsoper10 = sort.insertionSort(arrayGenerator.generateSortedToUp(1024));
        stopTime = System.nanoTime();
        long toupinstime10 = stopTime - startTime;
        startTime = System.nanoTime();
        int todowninsoper10 = sort.insertionSort(arrayGenerator.generateSortedToDown(1024));
        stopTime = System.nanoTime();
        long todowninstime10 = stopTime - startTime;
        startTime = System.nanoTime();
        int siminsoper110 = sort.insertionSort(arrayGenerator.generateSimpleArray(1024));
        int siminsoper210 = sort.insertionSort(arrayGenerator.generateSimpleArray(1024));
        int siminsoper310 = sort.insertionSort(arrayGenerator.generateSimpleArray(1024));
        stopTime = System.nanoTime();
        int siminsoper10 = (int)((siminsoper110+siminsoper210+siminsoper310) / 5);
        long siminstime10 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randmrgoper110 = sort.mergeSort(arrayGenerator.generateRandomArray(1024));
        int randmrgoper210 = sort.mergeSort(arrayGenerator.generateRandomArray(1024));
        int randmrgoper310 = sort.mergeSort(arrayGenerator.generateRandomArray(1024));
        int randmrgoper410 = sort.mergeSort(arrayGenerator.generateRandomArray(1024));
        int randmrgoper510 = sort.mergeSort(arrayGenerator.generateRandomArray(1024));
        stopTime = System.nanoTime();
        int randmrgoper10 = (int)((double)(randmrgoper110+randmrgoper210+randmrgoper310+randmrgoper410+randmrgoper510)/5);
        long randmrgtime10 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupmrgoper10 = sort.mergeSort(arrayGenerator.generateSortedToUp(1024));
        stopTime = System.nanoTime();
        long toupmrgtime10 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownmrgoper10 = sort.mergeSort(arrayGenerator.generateSortedToDown(1024));
        stopTime = System.nanoTime();
        long todownmrgtime10 = stopTime - startTime;
        startTime = System.nanoTime();
        int simmrgoper110 = sort.mergeSort(arrayGenerator.generateSimpleArray(1024));
        int simmrgoper210 = sort.mergeSort(arrayGenerator.generateSimpleArray(1024));
        int simmrgoper310 = sort.mergeSort(arrayGenerator.generateSimpleArray(1024));
        stopTime = System.nanoTime();
        int simmrgoper10 = (int)((simmrgoper110+simmrgoper210+simmrgoper310) / 5);
        long simmrgtime10 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randshloper110 = sort.shellSort(arrayGenerator.generateRandomArray(1024));
        int randshloper210 = sort.shellSort(arrayGenerator.generateRandomArray(1024));
        int randshloper310 = sort.shellSort(arrayGenerator.generateRandomArray(1024));
        int randshloper410 = sort.shellSort(arrayGenerator.generateRandomArray(1024));
        int randshloper510 = sort.shellSort(arrayGenerator.generateRandomArray(1024));
        stopTime = System.nanoTime();
        int randshloper10 = (int)((double)(randshloper110+randshloper210+randshloper310+randshloper410+randshloper510)/5);
        long randshltime10 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupshloper10 = sort.shellSort(arrayGenerator.generateSortedToUp(1024));
        stopTime = System.nanoTime();
        long toupshltime10 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownshloper10 = sort.shellSort(arrayGenerator.generateSortedToDown(1024));
        stopTime = System.nanoTime();
        long todownshltime10 = stopTime - startTime;
        startTime = System.nanoTime();
        int simshloper110 = sort.shellSort(arrayGenerator.generateSimpleArray(1024));
        int simshloper210 = sort.shellSort(arrayGenerator.generateSimpleArray(1024));
        int simshloper310 = sort.shellSort(arrayGenerator.generateSimpleArray(1024));
        stopTime = System.nanoTime();
        int simshloper10 = (int)((simshloper110+simshloper210+simshloper310) / 5);
        long simshltime10 = (stopTime - startTime) / 3;


        startTime = System.nanoTime();
        int randseloper111 = sort.selectionSort(arrayGenerator.generateRandomArray(2048));
        int randseloper211 = sort.selectionSort(arrayGenerator.generateRandomArray(2048));
        int randseloper311 = sort.selectionSort(arrayGenerator.generateRandomArray(2048));
        int randseloper411 = sort.selectionSort(arrayGenerator.generateRandomArray(2048));
        int randseloper511 = sort.selectionSort(arrayGenerator.generateRandomArray(2048));
        stopTime = System.nanoTime();
        int randseloper11 = (int)((double)(randseloper111+randseloper211+randseloper311+randseloper411+randseloper511)/5);
        long randseltime11 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupseloper11 = sort.selectionSort(arrayGenerator.generateSortedToUp(2048));
        stopTime = System.nanoTime();
        long toupseltime11 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownseloper11 = sort.selectionSort(arrayGenerator.generateSortedToDown(2048));
        stopTime = System.nanoTime();
        long todownseltime11 = stopTime - startTime;
        startTime = System.nanoTime();
        int simseloper111 = sort.selectionSort(arrayGenerator.generateSimpleArray(2048));
        int simseloper211 = sort.selectionSort(arrayGenerator.generateSimpleArray(2048));
        int simseloper311 = sort.selectionSort(arrayGenerator.generateSimpleArray(2048));
        stopTime = System.nanoTime();
        int simseloper11 = (int)((simseloper111+simseloper211+simseloper311) / 5);
        long simseltime11 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randinsoper111 = sort.insertionSort(arrayGenerator.generateRandomArray(2048));
        int randinsoper211 = sort.insertionSort(arrayGenerator.generateRandomArray(2048));
        int randinsoper311 = sort.insertionSort(arrayGenerator.generateRandomArray(2048));
        int randinsoper411 = sort.insertionSort(arrayGenerator.generateRandomArray(2048));
        int randinsoper511 = sort.insertionSort(arrayGenerator.generateRandomArray(2048));
        stopTime = System.nanoTime();
        int randinsoper11 = (int)((double)(randinsoper111+randinsoper211+randinsoper311+randinsoper411+randinsoper511)/5);
        long randinstime11 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupinsoper11 = sort.insertionSort(arrayGenerator.generateSortedToUp(2048));
        stopTime = System.nanoTime();
        long toupinstime11 = stopTime - startTime;
        startTime = System.nanoTime();
        int todowninsoper11 = sort.insertionSort(arrayGenerator.generateSortedToDown(2048));
        stopTime = System.nanoTime();
        long todowninstime11 = stopTime - startTime;
        startTime = System.nanoTime();
        int siminsoper111 = sort.insertionSort(arrayGenerator.generateSimpleArray(2048));
        int siminsoper211 = sort.insertionSort(arrayGenerator.generateSimpleArray(2048));
        int siminsoper311 = sort.insertionSort(arrayGenerator.generateSimpleArray(2048));
        stopTime = System.nanoTime();
        int siminsoper11 = (int)((siminsoper111+siminsoper211+siminsoper311) / 5);
        long siminstime11 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randmrgoper111 = sort.mergeSort(arrayGenerator.generateRandomArray(2048));
        int randmrgoper211 = sort.mergeSort(arrayGenerator.generateRandomArray(2048));
        int randmrgoper311 = sort.mergeSort(arrayGenerator.generateRandomArray(2048));
        int randmrgoper411 = sort.mergeSort(arrayGenerator.generateRandomArray(2048));
        int randmrgoper511 = sort.mergeSort(arrayGenerator.generateRandomArray(2048));
        stopTime = System.nanoTime();
        int randmrgoper11 = (int)((double)(randmrgoper111+randmrgoper211+randmrgoper311+randmrgoper411+randmrgoper511)/5);
        long randmrgtime11 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupmrgoper11 = sort.mergeSort(arrayGenerator.generateSortedToUp(2048));
        stopTime = System.nanoTime();
        long toupmrgtime11 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownmrgoper11 = sort.mergeSort(arrayGenerator.generateSortedToDown(2048));
        stopTime = System.nanoTime();
        long todownmrgtime11 = stopTime - startTime;
        startTime = System.nanoTime();
        int simmrgoper111 = sort.mergeSort(arrayGenerator.generateSimpleArray(2048));
        int simmrgoper211 = sort.mergeSort(arrayGenerator.generateSimpleArray(2048));
        int simmrgoper311 = sort.mergeSort(arrayGenerator.generateSimpleArray(2048));
        stopTime = System.nanoTime();
        int simmrgoper11 = (int)((simmrgoper111+simmrgoper211+simmrgoper311) / 5);
        long simmrgtime11 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randshloper111 = sort.shellSort(arrayGenerator.generateRandomArray(2048));
        int randshloper211 = sort.shellSort(arrayGenerator.generateRandomArray(2048));
        int randshloper311 = sort.shellSort(arrayGenerator.generateRandomArray(2048));
        int randshloper411 = sort.shellSort(arrayGenerator.generateRandomArray(2048));
        int randshloper511 = sort.shellSort(arrayGenerator.generateRandomArray(2048));
        stopTime = System.nanoTime();
        int randshloper11 = (int)((double)(randshloper111+randshloper211+randshloper311+randshloper411+randshloper511)/5);
        long randshltime11 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupshloper11 = sort.shellSort(arrayGenerator.generateSortedToUp(2048));
        stopTime = System.nanoTime();
        long toupshltime11 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownshloper11 = sort.shellSort(arrayGenerator.generateSortedToDown(2048));
        stopTime = System.nanoTime();
        long todownshltime11 = stopTime - startTime;
        startTime = System.nanoTime();
        int simshloper111 = sort.shellSort(arrayGenerator.generateSimpleArray(2048));
        int simshloper211 = sort.shellSort(arrayGenerator.generateSimpleArray(2048));
        int simshloper311 = sort.shellSort(arrayGenerator.generateSimpleArray(2048));
        stopTime = System.nanoTime();
        int simshloper11 = (int)((simshloper111+simshloper211+simshloper311) / 5);
        long simshltime11 = (stopTime - startTime) / 3;


        startTime = System.nanoTime();
        int randseloper112 = sort.selectionSort(arrayGenerator.generateRandomArray(4096));
        int randseloper212 = sort.selectionSort(arrayGenerator.generateRandomArray(4096));
        int randseloper312 = sort.selectionSort(arrayGenerator.generateRandomArray(4096));
        int randseloper412 = sort.selectionSort(arrayGenerator.generateRandomArray(4096));
        int randseloper512 = sort.selectionSort(arrayGenerator.generateRandomArray(4096));
        stopTime = System.nanoTime();
        int randseloper12 = (int)((double)(randseloper112+randseloper212+randseloper312+randseloper412+randseloper512)/5);
        long randseltime12 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupseloper12 = sort.selectionSort(arrayGenerator.generateSortedToUp(4096));
        stopTime = System.nanoTime();
        long toupseltime12 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownseloper12 = sort.selectionSort(arrayGenerator.generateSortedToDown(4096));
        stopTime = System.nanoTime();
        long todownseltime12 = stopTime - startTime;
        startTime = System.nanoTime();
        int simseloper112 = sort.selectionSort(arrayGenerator.generateSimpleArray(4096));
        int simseloper212 = sort.selectionSort(arrayGenerator.generateSimpleArray(4096));
        int simseloper312 = sort.selectionSort(arrayGenerator.generateSimpleArray(4096));
        stopTime = System.nanoTime();
        int simseloper12 = (int)((simseloper112+simseloper212+simseloper312) / 5);
        long simseltime12 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randinsoper112 = sort.insertionSort(arrayGenerator.generateRandomArray(4096));
        int randinsoper212 = sort.insertionSort(arrayGenerator.generateRandomArray(4096));
        int randinsoper312 = sort.insertionSort(arrayGenerator.generateRandomArray(4096));
        int randinsoper412 = sort.insertionSort(arrayGenerator.generateRandomArray(4096));
        int randinsoper512 = sort.insertionSort(arrayGenerator.generateRandomArray(4096));
        stopTime = System.nanoTime();
        int randinsoper12 = (int)((double)(randinsoper112+randinsoper212+randinsoper312+randinsoper412+randinsoper512)/5);
        long randinstime12 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupinsoper12 = sort.insertionSort(arrayGenerator.generateSortedToUp(4096));
        stopTime = System.nanoTime();
        long toupinstime12 = stopTime - startTime;
        startTime = System.nanoTime();
        int todowninsoper12 = sort.insertionSort(arrayGenerator.generateSortedToDown(4096));
        stopTime = System.nanoTime();
        long todowninstime12 = stopTime - startTime;
        startTime = System.nanoTime();
        int siminsoper112 = sort.insertionSort(arrayGenerator.generateSimpleArray(4096));
        int siminsoper212 = sort.insertionSort(arrayGenerator.generateSimpleArray(4096));
        int siminsoper312 = sort.insertionSort(arrayGenerator.generateSimpleArray(4096));
        stopTime = System.nanoTime();
        int siminsoper12 = (int)((siminsoper112+siminsoper212+siminsoper312) / 5);
        long siminstime12 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randmrgoper112 = sort.mergeSort(arrayGenerator.generateRandomArray(4096));
        int randmrgoper212 = sort.mergeSort(arrayGenerator.generateRandomArray(4096));
        int randmrgoper312 = sort.mergeSort(arrayGenerator.generateRandomArray(4096));
        int randmrgoper412 = sort.mergeSort(arrayGenerator.generateRandomArray(4096));
        int randmrgoper512 = sort.mergeSort(arrayGenerator.generateRandomArray(4096));
        stopTime = System.nanoTime();
        int randmrgoper12 = (int)((double)(randmrgoper112+randmrgoper212+randmrgoper312+randmrgoper412+randmrgoper512)/5);
        long randmrgtime12 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupmrgoper12 = sort.mergeSort(arrayGenerator.generateSortedToUp(4096));
        stopTime = System.nanoTime();
        long toupmrgtime12 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownmrgoper12 = sort.mergeSort(arrayGenerator.generateSortedToDown(4096));
        stopTime = System.nanoTime();
        long todownmrgtime12 = stopTime - startTime;
        startTime = System.nanoTime();
        int simmrgoper112 = sort.mergeSort(arrayGenerator.generateSimpleArray(4096));
        int simmrgoper212 = sort.mergeSort(arrayGenerator.generateSimpleArray(4096));
        int simmrgoper312 = sort.mergeSort(arrayGenerator.generateSimpleArray(4096));
        stopTime = System.nanoTime();
        int simmrgoper12 = (int)((simmrgoper112+simmrgoper212+simmrgoper312) / 5);
        long simmrgtime12 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randshloper112 = sort.shellSort(arrayGenerator.generateRandomArray(4096));
        int randshloper212 = sort.shellSort(arrayGenerator.generateRandomArray(4096));
        int randshloper312 = sort.shellSort(arrayGenerator.generateRandomArray(4096));
        int randshloper412 = sort.shellSort(arrayGenerator.generateRandomArray(4096));
        int randshloper512 = sort.shellSort(arrayGenerator.generateRandomArray(4096));
        stopTime = System.nanoTime();
        int randshloper12 = (int)((double)(randshloper112+randshloper212+randshloper312+randshloper412+randshloper512)/5);
        long randshltime12 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupshloper12 = sort.shellSort(arrayGenerator.generateSortedToUp(4096));
        stopTime = System.nanoTime();
        long toupshltime12 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownshloper12 = sort.shellSort(arrayGenerator.generateSortedToDown(4096));
        stopTime = System.nanoTime();
        long todownshltime12 = stopTime - startTime;
        startTime = System.nanoTime();
        int simshloper112 = sort.shellSort(arrayGenerator.generateSimpleArray(4096));
        int simshloper212 = sort.shellSort(arrayGenerator.generateSimpleArray(4096));
        int simshloper312 = sort.shellSort(arrayGenerator.generateSimpleArray(4096));
        stopTime = System.nanoTime();
        int simshloper12 = (int)((simshloper112+simshloper212+simshloper312) / 5);
        long simshltime12 = (stopTime - startTime) / 3;


        startTime = System.nanoTime();
        int randseloper113 = sort.selectionSort(arrayGenerator.generateRandomArray(8192));
        int randseloper213 = sort.selectionSort(arrayGenerator.generateRandomArray(8192));
        int randseloper313 = sort.selectionSort(arrayGenerator.generateRandomArray(8192));
        int randseloper413 = sort.selectionSort(arrayGenerator.generateRandomArray(8192));
        int randseloper513 = sort.selectionSort(arrayGenerator.generateRandomArray(8192));
        stopTime = System.nanoTime();
        int randseloper13 = (int)((double)(randseloper113+randseloper213+randseloper313+randseloper413+randseloper513)/5);
        long randseltime13 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupseloper13 = sort.selectionSort(arrayGenerator.generateSortedToUp(8192));
        stopTime = System.nanoTime();
        long toupseltime13 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownseloper13 = sort.selectionSort(arrayGenerator.generateSortedToDown(8192));
        stopTime = System.nanoTime();
        long todownseltime13 = stopTime - startTime;
        startTime = System.nanoTime();
        int simseloper113 = sort.selectionSort(arrayGenerator.generateSimpleArray(8192));
        int simseloper213 = sort.selectionSort(arrayGenerator.generateSimpleArray(8192));
        int simseloper313 = sort.selectionSort(arrayGenerator.generateSimpleArray(8192));
        stopTime = System.nanoTime();
        int simseloper13 = (int)((simseloper113+simseloper213+simseloper313) / 5);
        long simseltime13 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randinsoper113 = sort.insertionSort(arrayGenerator.generateRandomArray(8192));
        int randinsoper213 = sort.insertionSort(arrayGenerator.generateRandomArray(8192));
        int randinsoper313 = sort.insertionSort(arrayGenerator.generateRandomArray(8192));
        int randinsoper413 = sort.insertionSort(arrayGenerator.generateRandomArray(8192));
        int randinsoper513 = sort.insertionSort(arrayGenerator.generateRandomArray(8192));
        stopTime = System.nanoTime();
        int randinsoper13 = (int)((double)(randinsoper113+randinsoper213+randinsoper313+randinsoper413+randinsoper513)/5);
        long randinstime13 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupinsoper13 = sort.insertionSort(arrayGenerator.generateSortedToUp(8192));
        stopTime = System.nanoTime();
        long toupinstime13 = stopTime - startTime;
        startTime = System.nanoTime();
        int todowninsoper13 = sort.insertionSort(arrayGenerator.generateSortedToDown(8192));
        stopTime = System.nanoTime();
        long todowninstime13 = stopTime - startTime;
        startTime = System.nanoTime();
        int siminsoper113 = sort.insertionSort(arrayGenerator.generateSimpleArray(8192));
        int siminsoper213 = sort.insertionSort(arrayGenerator.generateSimpleArray(8192));
        int siminsoper313 = sort.insertionSort(arrayGenerator.generateSimpleArray(8192));
        stopTime = System.nanoTime();
        int siminsoper13 = (int)((siminsoper113+siminsoper213+siminsoper313) / 5);
        long siminstime13 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randmrgoper113 = sort.mergeSort(arrayGenerator.generateRandomArray(8192));
        int randmrgoper213 = sort.mergeSort(arrayGenerator.generateRandomArray(8192));
        int randmrgoper313 = sort.mergeSort(arrayGenerator.generateRandomArray(8192));
        int randmrgoper413 = sort.mergeSort(arrayGenerator.generateRandomArray(8192));
        int randmrgoper513 = sort.mergeSort(arrayGenerator.generateRandomArray(8192));
        stopTime = System.nanoTime();
        int randmrgoper13 = (int)((double)(randmrgoper113+randmrgoper213+randmrgoper313+randmrgoper413+randmrgoper513)/5);
        long randmrgtime13 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupmrgoper13 = sort.mergeSort(arrayGenerator.generateSortedToUp(8192));
        stopTime = System.nanoTime();
        long toupmrgtime13 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownmrgoper13 = sort.mergeSort(arrayGenerator.generateSortedToDown(8192));
        stopTime = System.nanoTime();
        long todownmrgtime13 = stopTime - startTime;
        startTime = System.nanoTime();
        int simmrgoper113 = sort.mergeSort(arrayGenerator.generateSimpleArray(8192));
        int simmrgoper213 = sort.mergeSort(arrayGenerator.generateSimpleArray(8192));
        int simmrgoper313 = sort.mergeSort(arrayGenerator.generateSimpleArray(8192));
        stopTime = System.nanoTime();
        int simmrgoper13 = (int)((simmrgoper113+simmrgoper213+simmrgoper313) / 5);
        long simmrgtime13 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randshloper113 = sort.shellSort(arrayGenerator.generateRandomArray(8192));
        int randshloper213 = sort.shellSort(arrayGenerator.generateRandomArray(8192));
        int randshloper313 = sort.shellSort(arrayGenerator.generateRandomArray(8192));
        int randshloper413 = sort.shellSort(arrayGenerator.generateRandomArray(8192));
        int randshloper513 = sort.shellSort(arrayGenerator.generateRandomArray(8192));
        stopTime = System.nanoTime();
        int randshloper13 = (int)((double)(randshloper113+randshloper213+randshloper313+randshloper413+randshloper513)/5);
        long randshltime13 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupshloper13 = sort.shellSort(arrayGenerator.generateSortedToUp(8192));
        stopTime = System.nanoTime();
        long toupshltime13 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownshloper13 = sort.shellSort(arrayGenerator.generateSortedToDown(8192));
        stopTime = System.nanoTime();
        long todownshltime13 = stopTime - startTime;
        startTime = System.nanoTime();
        int simshloper113 = sort.shellSort(arrayGenerator.generateSimpleArray(8192));
        int simshloper213 = sort.shellSort(arrayGenerator.generateSimpleArray(8192));
        int simshloper313 = sort.shellSort(arrayGenerator.generateSimpleArray(8192));
        stopTime = System.nanoTime();
        int simshloper13 = (int)((simshloper113+simshloper213+simshloper313) / 5);
        long simshltime13 = (stopTime - startTime) / 3;


        startTime = System.nanoTime();
        int randseloper114 = sort.selectionSort(arrayGenerator.generateRandomArray(16384));
        int randseloper214 = sort.selectionSort(arrayGenerator.generateRandomArray(16384));
        int randseloper314 = sort.selectionSort(arrayGenerator.generateRandomArray(16384));
        int randseloper414 = sort.selectionSort(arrayGenerator.generateRandomArray(16384));
        int randseloper514 = sort.selectionSort(arrayGenerator.generateRandomArray(16384));
        stopTime = System.nanoTime();
        int randseloper14 = (int)((double)(randseloper114+randseloper214+randseloper314+randseloper414+randseloper514)/5);
        long randseltime14 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupseloper14 = sort.selectionSort(arrayGenerator.generateSortedToUp(16384));
        stopTime = System.nanoTime();
        long toupseltime14 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownseloper14 = sort.selectionSort(arrayGenerator.generateSortedToDown(16384));
        stopTime = System.nanoTime();
        long todownseltime14 = stopTime - startTime;
        startTime = System.nanoTime();
        int simseloper114 = sort.selectionSort(arrayGenerator.generateSimpleArray(16384));
        int simseloper214 = sort.selectionSort(arrayGenerator.generateSimpleArray(16384));
        int simseloper314 = sort.selectionSort(arrayGenerator.generateSimpleArray(16384));
        stopTime = System.nanoTime();
        int simseloper14 = (int)((simseloper114+simseloper214+simseloper314) / 5);
        long simseltime14 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randinsoper114 = sort.insertionSort(arrayGenerator.generateRandomArray(16384));
        int randinsoper214 = sort.insertionSort(arrayGenerator.generateRandomArray(16384));
        int randinsoper314 = sort.insertionSort(arrayGenerator.generateRandomArray(16384));
        int randinsoper414 = sort.insertionSort(arrayGenerator.generateRandomArray(16384));
        int randinsoper514 = sort.insertionSort(arrayGenerator.generateRandomArray(16384));
        stopTime = System.nanoTime();
        int randinsoper14 = (int)((double)(randinsoper114+randinsoper214+randinsoper314+randinsoper414+randinsoper514)/5);
        long randinstime14 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupinsoper14 = sort.insertionSort(arrayGenerator.generateSortedToUp(16384));
        stopTime = System.nanoTime();
        long toupinstime14 = stopTime - startTime;
        startTime = System.nanoTime();
        int todowninsoper14 = sort.insertionSort(arrayGenerator.generateSortedToDown(16384));
        stopTime = System.nanoTime();
        long todowninstime14 = stopTime - startTime;
        startTime = System.nanoTime();
        int siminsoper114 = sort.insertionSort(arrayGenerator.generateSimpleArray(16384));
        int siminsoper214 = sort.insertionSort(arrayGenerator.generateSimpleArray(16384));
        int siminsoper314 = sort.insertionSort(arrayGenerator.generateSimpleArray(16384));
        stopTime = System.nanoTime();
        int siminsoper14 = (int)((siminsoper114+siminsoper214+siminsoper314) / 5);
        long siminstime14 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randmrgoper114 = sort.mergeSort(arrayGenerator.generateRandomArray(16384));
        int randmrgoper214 = sort.mergeSort(arrayGenerator.generateRandomArray(16384));
        int randmrgoper314 = sort.mergeSort(arrayGenerator.generateRandomArray(16384));
        int randmrgoper414 = sort.mergeSort(arrayGenerator.generateRandomArray(16384));
        int randmrgoper514 = sort.mergeSort(arrayGenerator.generateRandomArray(16384));
        stopTime = System.nanoTime();
        int randmrgoper14 = (int)((double)(randmrgoper114+randmrgoper214+randmrgoper314+randmrgoper414+randmrgoper514)/5);
        long randmrgtime14 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupmrgoper14 = sort.mergeSort(arrayGenerator.generateSortedToUp(16384));
        stopTime = System.nanoTime();
        long toupmrgtime14 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownmrgoper14 = sort.mergeSort(arrayGenerator.generateSortedToDown(16384));
        stopTime = System.nanoTime();
        long todownmrgtime14 = stopTime - startTime;
        startTime = System.nanoTime();
        int simmrgoper114 = sort.mergeSort(arrayGenerator.generateSimpleArray(16384));
        int simmrgoper214 = sort.mergeSort(arrayGenerator.generateSimpleArray(16384));
        int simmrgoper314 = sort.mergeSort(arrayGenerator.generateSimpleArray(16384));
        stopTime = System.nanoTime();
        int simmrgoper14 = (int)((simmrgoper114+simmrgoper214+simmrgoper314) / 5);
        long simmrgtime14 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randshloper114 = sort.shellSort(arrayGenerator.generateRandomArray(16384));
        int randshloper214 = sort.shellSort(arrayGenerator.generateRandomArray(16384));
        int randshloper314 = sort.shellSort(arrayGenerator.generateRandomArray(16384));
        int randshloper414 = sort.shellSort(arrayGenerator.generateRandomArray(16384));
        int randshloper514 = sort.shellSort(arrayGenerator.generateRandomArray(16384));
        stopTime = System.nanoTime();
        int randshloper14 = (int)((double)(randshloper114+randshloper214+randshloper314+randshloper414+randshloper514)/5);
        long randshltime14 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupshloper14 = sort.shellSort(arrayGenerator.generateSortedToUp(16384));
        stopTime = System.nanoTime();
        long toupshltime14 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownshloper14 = sort.shellSort(arrayGenerator.generateSortedToDown(16384));
        stopTime = System.nanoTime();
        long todownshltime14 = stopTime - startTime;
        startTime = System.nanoTime();
        int simshloper114 = sort.shellSort(arrayGenerator.generateSimpleArray(16384));
        int simshloper214 = sort.shellSort(arrayGenerator.generateSimpleArray(16384));
        int simshloper314 = sort.shellSort(arrayGenerator.generateSimpleArray(16384));
        stopTime = System.nanoTime();
        int simshloper14 = (int)((simshloper114+simshloper214+simshloper314) / 5);
        long simshltime14 = (stopTime - startTime) / 3;


        startTime = System.nanoTime();
        int randseloper115 = sort.selectionSort(arrayGenerator.generateRandomArray(32768));
        int randseloper215 = sort.selectionSort(arrayGenerator.generateRandomArray(32768));
        int randseloper315 = sort.selectionSort(arrayGenerator.generateRandomArray(32768));
        int randseloper415 = sort.selectionSort(arrayGenerator.generateRandomArray(32768));
        int randseloper515 = sort.selectionSort(arrayGenerator.generateRandomArray(32768));
        stopTime = System.nanoTime();
        int randseloper15 = (int)((double)(randseloper115+randseloper215+randseloper315+randseloper415+randseloper515)/5);
        long randseltime15 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupseloper15 = sort.selectionSort(arrayGenerator.generateSortedToUp(32768));
        stopTime = System.nanoTime();
        long toupseltime15 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownseloper15 = sort.selectionSort(arrayGenerator.generateSortedToDown(32768));
        stopTime = System.nanoTime();
        long todownseltime15 = stopTime - startTime;
        startTime = System.nanoTime();
        int simseloper115 = sort.selectionSort(arrayGenerator.generateSimpleArray(32768));
        int simseloper215 = sort.selectionSort(arrayGenerator.generateSimpleArray(32768));
        int simseloper315 = sort.selectionSort(arrayGenerator.generateSimpleArray(32768));
        stopTime = System.nanoTime();
        int simseloper15 = (int)((simseloper115+simseloper215+simseloper315) / 5);
        long simseltime15 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randinsoper115 = sort.insertionSort(arrayGenerator.generateRandomArray(32768));
        int randinsoper215 = sort.insertionSort(arrayGenerator.generateRandomArray(32768));
        int randinsoper315 = sort.insertionSort(arrayGenerator.generateRandomArray(32768));
        int randinsoper415 = sort.insertionSort(arrayGenerator.generateRandomArray(32768));
        int randinsoper515 = sort.insertionSort(arrayGenerator.generateRandomArray(32768));
        stopTime = System.nanoTime();
        int randinsoper15 = (int)((double)(randinsoper115+randinsoper215+randinsoper315+randinsoper415+randinsoper515)/5);
        long randinstime15 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupinsoper15 = sort.insertionSort(arrayGenerator.generateSortedToUp(32768));
        stopTime = System.nanoTime();
        long toupinstime15 = stopTime - startTime;
        startTime = System.nanoTime();
        int todowninsoper15 = sort.insertionSort(arrayGenerator.generateSortedToDown(32768));
        stopTime = System.nanoTime();
        long todowninstime15 = stopTime - startTime;
        startTime = System.nanoTime();
        int siminsoper115 = sort.insertionSort(arrayGenerator.generateSimpleArray(32768));
        int siminsoper215 = sort.insertionSort(arrayGenerator.generateSimpleArray(32768));
        int siminsoper315 = sort.insertionSort(arrayGenerator.generateSimpleArray(32768));
        stopTime = System.nanoTime();
        int siminsoper15 = (int)((siminsoper115+siminsoper215+siminsoper315) / 5);
        long siminstime15 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randmrgoper115 = sort.mergeSort(arrayGenerator.generateRandomArray(32768));
        int randmrgoper215 = sort.mergeSort(arrayGenerator.generateRandomArray(32768));
        int randmrgoper315 = sort.mergeSort(arrayGenerator.generateRandomArray(32768));
        int randmrgoper415 = sort.mergeSort(arrayGenerator.generateRandomArray(32768));
        int randmrgoper515 = sort.mergeSort(arrayGenerator.generateRandomArray(32768));
        stopTime = System.nanoTime();
        int randmrgoper15 = (int)((double)(randmrgoper115+randmrgoper215+randmrgoper315+randmrgoper415+randmrgoper515)/5);
        long randmrgtime15 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupmrgoper15 = sort.mergeSort(arrayGenerator.generateSortedToUp(32768));
        stopTime = System.nanoTime();
        long toupmrgtime15 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownmrgoper15 = sort.mergeSort(arrayGenerator.generateSortedToDown(32768));
        stopTime = System.nanoTime();
        long todownmrgtime15 = stopTime - startTime;
        startTime = System.nanoTime();
        int simmrgoper115 = sort.mergeSort(arrayGenerator.generateSimpleArray(32768));
        int simmrgoper215 = sort.mergeSort(arrayGenerator.generateSimpleArray(32768));
        int simmrgoper315 = sort.mergeSort(arrayGenerator.generateSimpleArray(32768));
        stopTime = System.nanoTime();
        int simmrgoper15 = (int)((simmrgoper115+simmrgoper215+simmrgoper315) / 5);
        long simmrgtime15 = (stopTime - startTime) / 3;

        startTime = System.nanoTime();
        int randshloper115 = sort.shellSort(arrayGenerator.generateRandomArray(32768));
        int randshloper215 = sort.shellSort(arrayGenerator.generateRandomArray(32768));
        int randshloper315 = sort.shellSort(arrayGenerator.generateRandomArray(32768));
        int randshloper415 = sort.shellSort(arrayGenerator.generateRandomArray(32768));
        int randshloper515 = sort.shellSort(arrayGenerator.generateRandomArray(32768));
        stopTime = System.nanoTime();
        int randshloper15 = (int)((double)(randshloper115+randshloper215+randshloper315+randshloper415+randshloper515)/5);
        long randshltime15 = (stopTime - startTime) / 5;
        startTime = System.nanoTime();
        int toupshloper15 = sort.shellSort(arrayGenerator.generateSortedToUp(32768));
        stopTime = System.nanoTime();
        long toupshltime15 = stopTime - startTime;
        startTime = System.nanoTime();
        int todownshloper15 = sort.shellSort(arrayGenerator.generateSortedToDown(32768));
        stopTime = System.nanoTime();
        long todownshltime15 = stopTime - startTime;
        startTime = System.nanoTime();
        int simshloper115 = sort.shellSort(arrayGenerator.generateSimpleArray(32768));
        int simshloper215 = sort.shellSort(arrayGenerator.generateSimpleArray(32768));
        int simshloper315 = sort.shellSort(arrayGenerator.generateSimpleArray(32768));
        stopTime = System.nanoTime();
        int simshloper15 = (int)((simshloper115+simshloper215+simshloper315) / 5);
        long simshltime15 = (stopTime - startTime) / 3;

        // Printing results
        System.out.println("Time for random array, selection sort, 2^7 size: " + randseltime7);
        System.out.println("Operations for random array, selection sort, 2^7 size: " + randseloper7);
        System.out.println("Time for sorted to up array, selection sort, 2^7 size: " + toupseltime7);
        System.out.println("Operations for sorted to up array, selection sort, 2^7 size: " + toupseloper7);
        System.out.println("Time for sorted to down array, selection sort, 2^7 size: " + todownseltime7);
        System.out.println("Operations for sorted to down array, selection sort, 2^7 size: " + todownseloper7);
        System.out.println("Time for simple array, selection sort, 2^7 size: " + simseltime7);
        System.out.println("Operations for simple array, selection sort, 2^7 size: " + simseloper7);

        System.out.println("Time for random array, insertion sort, 2^7 size: " + randinstime7);
        System.out.println("Operations for random array, insertion sort, 2^7 size: " + randinsoper7);
        System.out.println("Time for sorted to up array, insertion sort, 2^7 size: " + toupinstime7);
        System.out.println("Operations for sorted to up array, insertion sort, 2^7 size: " + toupinsoper7);
        System.out.println("Time for sorted to down array, insertion sort, 2^7 size: " + todowninstime7);
        System.out.println("Operations for sorted to down array, insertion sort, 2^7 size: " + todowninsoper7);
        System.out.println("Time for simple array, insertion sort, 2^7 size: " + siminstime7);
        System.out.println("Operations for simple array, insertion sort, 2^7 size: " + siminsoper7);

        System.out.println("Time for random array, merge sort, 2^7 size: " + randmrgtime7);
        System.out.println("Operations for random array, merge sort, 2^7 size: " + randmrgoper7);
        System.out.println("Time for sorted to up array, merge sort, 2^7 size: " + toupmrgtime7);
        System.out.println("Operations for sorted to up array, merge sort, 2^7 size: " + toupmrgoper7);
        System.out.println("Time for sorted to down array, merge sort, 2^7 size: " + todownmrgtime7);
        System.out.println("Operations for sorted to down array, merge sort, 2^7 size: " + todownmrgoper7);
        System.out.println("Time for simple array, merge sort, 2^7 size: " + simmrgtime7);
        System.out.println("Operations for simple array, merge sort, 2^7 size: " + simmrgoper7);

        System.out.println("Time for random array, shell sort, 2^7 size: " + randshltime7);
        System.out.println("Operations for random array, shell sort, 2^7 size: " + randshloper7);
        System.out.println("Time for sorted to up array, shell sort, 2^7 size: " + toupshltime7);
        System.out.println("Operations for sorted to up array, shell sort, 2^7 size: " + toupshloper7);
        System.out.println("Time for sorted to down array, shell sort, 2^7 size: " + todownshltime7);
        System.out.println("Operations for sorted to down array, shell sort, 2^7 size: " + todownshloper7);
        System.out.println("Time for simple array, shell sort, 2^7 size: " + simshltime7);
        System.out.println("Operations for simple array, shell sort, 2^7 size: " + simshloper7);

        System.out.println("Time for random array, selection sort, 2^8 size: " + randseltime8);
        System.out.println("Operations for random array, selection sort, 2^8 size: " + randseloper8);
        System.out.println("Time for sorted to up array, selection sort, 2^8 size: " + toupseltime8);
        System.out.println("Operations for sorted to up array, selection sort, 2^8 size: " + toupseloper8);
        System.out.println("Time for sorted to down array, selection sort, 2^8 size: " + todownseltime8);
        System.out.println("Operations for sorted to down array, selection sort, 2^8 size: " + todownseloper8);
        System.out.println("Time for simple array, selection sort, 2^8 size: " + simseltime8);
        System.out.println("Operations for simple array, selection sort, 2^8 size: " + simseloper8);

        System.out.println("Time for random array, insertion sort, 2^8 size: " + randinstime8);
        System.out.println("Operations for random array, insertion sort, 2^8 size: " + randinsoper8);
        System.out.println("Time for sorted to up array, insertion sort, 2^8 size: " + toupinstime8);
        System.out.println("Operations for sorted to up array, insertion sort, 2^8 size: " + toupinsoper8);
        System.out.println("Time for sorted to down array, insertion sort, 2^8 size: " + todowninstime8);
        System.out.println("Operations for sorted to down array, insertion sort, 2^8 size: " + todowninsoper8);
        System.out.println("Time for simple array, insertion sort, 2^8 size: " + siminstime8);
        System.out.println("Operations for simple array, insertion sort, 2^8 size: " + siminsoper8);

        System.out.println("Time for random array, merge sort, 2^8 size: " + randmrgtime8);
        System.out.println("Operations for random array, merge sort, 2^8 size: " + randmrgoper8);
        System.out.println("Time for sorted to up array, merge sort, 2^8 size: " + toupmrgtime8);
        System.out.println("Operations for sorted to up array, merge sort, 2^8 size: " + toupmrgoper8);
        System.out.println("Time for sorted to down array, merge sort, 2^8 size: " + todownmrgtime8);
        System.out.println("Operations for sorted to down array, merge sort, 2^8 size: " + todownmrgoper8);
        System.out.println("Time for simple array, merge sort, 2^8 size: " + simmrgtime8);
        System.out.println("Operations for simple array, merge sort, 2^8 size: " + simmrgoper8);

        System.out.println("Time for random array, shell sort, 2^8 size: " + randshltime8);
        System.out.println("Operations for random array, shell sort, 2^8 size: " + randshloper8);
        System.out.println("Time for sorted to up array, shell sort, 2^8 size: " + toupshltime8);
        System.out.println("Operations for sorted to up array, shell sort, 2^8 size: " + toupshloper8);
        System.out.println("Time for sorted to down array, shell sort, 2^8 size: " + todownshltime8);
        System.out.println("Operations for sorted to down array, shell sort, 2^8 size: " + todownshloper8);
        System.out.println("Time for simple array, shell sort, 2^8 size: " + simshltime8);
        System.out.println("Operations for simple array, shell sort, 2^8 size: " + simshloper8);


        System.out.println("Time for random array, selection sort, 2^9 size: " + randseltime9);
        System.out.println("Operations for random array, selection sort, 2^9 size: " + randseloper9);
        System.out.println("Time for sorted to up array, selection sort, 2^9 size: " + toupseltime9);
        System.out.println("Operations for sorted to up array, selection sort, 2^9 size: " + toupseloper9);
        System.out.println("Time for sorted to down array, selection sort, 2^9 size: " + todownseltime9);
        System.out.println("Operations for sorted to down array, selection sort, 2^9 size: " + todownseloper9);
        System.out.println("Time for simple array, selection sort, 2^9 size: " + simseltime9);
        System.out.println("Operations for simple array, selection sort, 2^9 size: " + simseloper9);

        System.out.println("Time for random array, insertion sort, 2^9 size: " + randinstime9);
        System.out.println("Operations for random array, insertion sort, 2^9 size: " + randinsoper9);
        System.out.println("Time for sorted to up array, insertion sort, 2^9 size: " + toupinstime9);
        System.out.println("Operations for sorted to up array, insertion sort, 2^9 size: " + toupinsoper9);
        System.out.println("Time for sorted to down array, insertion sort, 2^9 size: " + todowninstime9);
        System.out.println("Operations for sorted to down array, insertion sort, 2^9 size: " + todowninsoper9);
        System.out.println("Time for simple array, insertion sort, 2^9 size: " + siminstime9);
        System.out.println("Operations for simple array, insertion sort, 2^9 size: " + siminsoper9);

        System.out.println("Time for random array, merge sort, 2^9 size: " + randmrgtime9);
        System.out.println("Operations for random array, merge sort, 2^9 size: " + randmrgoper9);
        System.out.println("Time for sorted to up array, merge sort, 2^9 size: " + toupmrgtime9);
        System.out.println("Operations for sorted to up array, merge sort, 2^9 size: " + toupmrgoper9);
        System.out.println("Time for sorted to down array, merge sort, 2^9 size: " + todownmrgtime9);
        System.out.println("Operations for sorted to down array, merge sort, 2^9 size: " + todownmrgoper9);
        System.out.println("Time for simple array, merge sort, 2^9 size: " + simmrgtime9);
        System.out.println("Operations for simple array, merge sort, 2^9 size: " + simmrgoper9);

        System.out.println("Time for random array, shell sort, 2^9 size: " + randshltime9);
        System.out.println("Operations for random array, shell sort, 2^9 size: " + randshloper9);
        System.out.println("Time for sorted to up array, shell sort, 2^9 size: " + toupshltime9);
        System.out.println("Operations for sorted to up array, shell sort, 2^9 size: " + toupshloper9);
        System.out.println("Time for sorted to down array, shell sort, 2^9 size: " + todownshltime9);
        System.out.println("Operations for sorted to down array, shell sort, 2^9 size: " + todownshloper9);
        System.out.println("Time for simple array, shell sort, 2^9 size: " + simshltime9);
        System.out.println("Operations for simple array, shell sort, 2^9 size: " + simshloper9);


        System.out.println("Time for random array, selection sort, 2^10 size: " + randseltime10);
        System.out.println("Operations for random array, selection sort, 2^10 size: " + randseloper10);
        System.out.println("Time for sorted to up array, selection sort, 2^10 size: " + toupseltime10);
        System.out.println("Operations for sorted to up array, selection sort, 2^10 size: " + toupseloper10);
        System.out.println("Time for sorted to down array, selection sort, 2^10 size: " + todownseltime10);
        System.out.println("Operations for sorted to down array, selection sort, 2^10 size: " + todownseloper10);
        System.out.println("Time for simple array, selection sort, 2^10 size: " + simseltime10);
        System.out.println("Operations for simple array, selection sort, 2^10 size: " + simseloper10);

        System.out.println("Time for random array, insertion sort, 2^10 size: " + randinstime10);
        System.out.println("Operations for random array, insertion sort, 2^10 size: " + randinsoper10);
        System.out.println("Time for sorted to up array, insertion sort, 2^10 size: " + toupinstime10);
        System.out.println("Operations for sorted to up array, insertion sort, 2^10 size: " + toupinsoper10);
        System.out.println("Time for sorted to down array, insertion sort, 2^10 size: " + todowninstime10);
        System.out.println("Operations for sorted to down array, insertion sort, 2^10 size: " + todowninsoper10);
        System.out.println("Time for simple array, insertion sort, 2^10 size: " + siminstime10);
        System.out.println("Operations for simple array, insertion sort, 2^10 size: " + siminsoper10);

        System.out.println("Time for random array, merge sort, 2^10 size: " + randmrgtime10);
        System.out.println("Operations for random array, merge sort, 2^10 size: " + randmrgoper10);
        System.out.println("Time for sorted to up array, merge sort, 2^10 size: " + toupmrgtime10);
        System.out.println("Operations for sorted to up array, merge sort, 2^10 size: " + toupmrgoper10);
        System.out.println("Time for sorted to down array, merge sort, 2^10 size: " + todownmrgtime10);
        System.out.println("Operations for sorted to down array, merge sort, 2^10 size: " + todownmrgoper10);
        System.out.println("Time for simple array, merge sort, 2^10 size: " + simmrgtime10);
        System.out.println("Operations for simple array, merge sort, 2^10 size: " + simmrgoper10);

        System.out.println("Time for random array, shell sort, 2^10 size: " + randshltime10);
        System.out.println("Operations for random array, shell sort, 2^10 size: " + randshloper10);
        System.out.println("Time for sorted to up array, shell sort, 2^10 size: " + toupshltime10);
        System.out.println("Operations for sorted to up array, shell sort, 2^10 size: " + toupshloper10);
        System.out.println("Time for sorted to down array, shell sort, 2^10 size: " + todownshltime10);
        System.out.println("Operations for sorted to down array, shell sort, 2^10 size: " + todownshloper10);
        System.out.println("Time for simple array, shell sort, 2^10 size: " + simshltime10);
        System.out.println("Operations for simple array, shell sort, 2^10 size: " + simshloper10);


        System.out.println("Time for random array, selection sort, 2^11 size: " + randseltime11);
        System.out.println("Operations for random array, selection sort, 2^11 size: " + randseloper11);
        System.out.println("Time for sorted to up array, selection sort, 2^11 size: " + toupseltime11);
        System.out.println("Operations for sorted to up array, selection sort, 2^11 size: " + toupseloper11);
        System.out.println("Time for sorted to down array, selection sort, 2^11 size: " + todownseltime11);
        System.out.println("Operations for sorted to down array, selection sort, 2^11 size: " + todownseloper11);
        System.out.println("Time for simple array, selection sort, 2^11 size: " + simseltime11);
        System.out.println("Operations for simple array, selection sort, 2^11 size: " + simseloper11);

        System.out.println("Time for random array, insertion sort, 2^11 size: " + randinstime11);
        System.out.println("Operations for random array, insertion sort, 2^11 size: " + randinsoper11);
        System.out.println("Time for sorted to up array, insertion sort, 2^11 size: " + toupinstime11);
        System.out.println("Operations for sorted to up array, insertion sort, 2^11 size: " + toupinsoper11);
        System.out.println("Time for sorted to down array, insertion sort, 2^11 size: " + todowninstime11);
        System.out.println("Operations for sorted to down array, insertion sort, 2^11 size: " + todowninsoper11);
        System.out.println("Time for simple array, insertion sort, 2^11 size: " + siminstime11);
        System.out.println("Operations for simple array, insertion sort, 2^11 size: " + siminsoper11);

        System.out.println("Time for random array, merge sort, 2^11 size: " + randmrgtime11);
        System.out.println("Operations for random array, merge sort, 2^11 size: " + randmrgoper11);
        System.out.println("Time for sorted to up array, merge sort, 2^11 size: " + toupmrgtime11);
        System.out.println("Operations for sorted to up array, merge sort, 2^11 size: " + toupmrgoper11);
        System.out.println("Time for sorted to down array, merge sort, 2^11 size: " + todownmrgtime11);
        System.out.println("Operations for sorted to down array, merge sort, 2^11 size: " + todownmrgoper11);
        System.out.println("Time for simple array, merge sort, 2^11 size: " + simmrgtime11);
        System.out.println("Operations for simple array, merge sort, 2^11 size: " + simmrgoper11);

        System.out.println("Time for random array, shell sort, 2^11 size: " + randshltime11);
        System.out.println("Operations for random array, shell sort, 2^11 size: " + randshloper11);
        System.out.println("Time for sorted to up array, shell sort, 2^11 size: " + toupshltime11);
        System.out.println("Operations for sorted to up array, shell sort, 2^11 size: " + toupshloper11);
        System.out.println("Time for sorted to down array, shell sort, 2^11 size: " + todownshltime11);
        System.out.println("Operations for sorted to down array, shell sort, 2^11 size: " + todownshloper11);
        System.out.println("Time for simple array, shell sort, 2^11 size: " + simshltime11);
        System.out.println("Operations for simple array, shell sort, 2^11 size: " + simshloper11);
        

        System.out.println("Time for random array, selection sort, 2^12 size: " + randseltime12);
        System.out.println("Operations for random array, selection sort, 2^12 size: " + randseloper12);
        System.out.println("Time for sorted to up array, selection sort, 2^12 size: " + toupseltime12);
        System.out.println("Operations for sorted to up array, selection sort, 2^12 size: " + toupseloper12);
        System.out.println("Time for sorted to down array, selection sort, 2^12 size: " + todownseltime12);
        System.out.println("Operations for sorted to down array, selection sort, 2^12 size: " + todownseloper12);
        System.out.println("Time for simple array, selection sort, 2^12 size: " + simseltime12);
        System.out.println("Operations for simple array, selection sort, 2^12 size: " + simseloper12);

        System.out.println("Time for random array, insertion sort, 2^12 size: " + randinstime12);
        System.out.println("Operations for random array, insertion sort, 2^12 size: " + randinsoper12);
        System.out.println("Time for sorted to up array, insertion sort, 2^12 size: " + toupinstime12);
        System.out.println("Operations for sorted to up array, insertion sort, 2^12 size: " + toupinsoper12);
        System.out.println("Time for sorted to down array, insertion sort, 2^12 size: " + todowninstime12);
        System.out.println("Operations for sorted to down array, insertion sort, 2^12 size: " + todowninsoper12);
        System.out.println("Time for simple array, insertion sort, 2^12 size: " + siminstime12);
        System.out.println("Operations for simple array, insertion sort, 2^12 size: " + siminsoper12);

        System.out.println("Time for random array, merge sort, 2^12 size: " + randmrgtime12);
        System.out.println("Operations for random array, merge sort, 2^12 size: " + randmrgoper12);
        System.out.println("Time for sorted to up array, merge sort, 2^12 size: " + toupmrgtime12);
        System.out.println("Operations for sorted to up array, merge sort, 2^12 size: " + toupmrgoper12);
        System.out.println("Time for sorted to down array, merge sort, 2^12 size: " + todownmrgtime12);
        System.out.println("Operations for sorted to down array, merge sort, 2^12 size: " + todownmrgoper12);
        System.out.println("Time for simple array, merge sort, 2^12 size: " + simmrgtime12);
        System.out.println("Operations for simple array, merge sort, 2^12 size: " + simmrgoper12);

        System.out.println("Time for random array, shell sort, 2^12 size: " + randshltime12);
        System.out.println("Operations for random array, shell sort, 2^12 size: " + randshloper12);
        System.out.println("Time for sorted to up array, shell sort, 2^12 size: " + toupshltime12);
        System.out.println("Operations for sorted to up array, shell sort, 2^12 size: " + toupshloper12);
        System.out.println("Time for sorted to down array, shell sort, 2^12 size: " + todownshltime12);
        System.out.println("Operations for sorted to down array, shell sort, 2^12 size: " + todownshloper12);
        System.out.println("Time for simple array, shell sort, 2^12 size: " + simshltime12);
        System.out.println("Operations for simple array, shell sort, 2^12 size: " + simshloper12);


        System.out.println("Time for random array, selection sort, 2^13 size: " + randseltime13);
        System.out.println("Operations for random array, selection sort, 2^13 size: " + randseloper13);
        System.out.println("Time for sorted to up array, selection sort, 2^13 size: " + toupseltime13);
        System.out.println("Operations for sorted to up array, selection sort, 2^13 size: " + toupseloper13);
        System.out.println("Time for sorted to down array, selection sort, 2^13 size: " + todownseltime13);
        System.out.println("Operations for sorted to down array, selection sort, 2^13 size: " + todownseloper13);
        System.out.println("Time for simple array, selection sort, 2^13 size: " + simseltime13);
        System.out.println("Operations for simple array, selection sort, 2^13 size: " + simseloper13);

        System.out.println("Time for random array, insertion sort, 2^13 size: " + randinstime13);
        System.out.println("Operations for random array, insertion sort, 2^13 size: " + randinsoper13);
        System.out.println("Time for sorted to up array, insertion sort, 2^13 size: " + toupinstime13);
        System.out.println("Operations for sorted to up array, insertion sort, 2^13 size: " + toupinsoper13);
        System.out.println("Time for sorted to down array, insertion sort, 2^13 size: " + todowninstime13);
        System.out.println("Operations for sorted to down array, insertion sort, 2^13 size: " + todowninsoper13);
        System.out.println("Time for simple array, insertion sort, 2^13 size: " + siminstime13);
        System.out.println("Operations for simple array, insertion sort, 2^13 size: " + siminsoper13);

        System.out.println("Time for random array, merge sort, 2^13 size: " + randmrgtime13);
        System.out.println("Operations for random array, merge sort, 2^13 size: " + randmrgoper13);
        System.out.println("Time for sorted to up array, merge sort, 2^13 size: " + toupmrgtime13);
        System.out.println("Operations for sorted to up array, merge sort, 2^13 size: " + toupmrgoper13);
        System.out.println("Time for sorted to down array, merge sort, 2^13 size: " + todownmrgtime13);
        System.out.println("Operations for sorted to down array, merge sort, 2^13 size: " + todownmrgoper13);
        System.out.println("Time for simple array, merge sort, 2^13 size: " + simmrgtime13);
        System.out.println("Operations for simple array, merge sort, 2^13 size: " + simmrgoper13);

        System.out.println("Time for random array, shell sort, 2^13 size: " + randshltime13);
        System.out.println("Operations for random array, shell sort, 2^13 size: " + randshloper13);
        System.out.println("Time for sorted to up array, shell sort, 2^13 size: " + toupshltime13);
        System.out.println("Operations for sorted to up array, shell sort, 2^13 size: " + toupshloper13);
        System.out.println("Time for sorted to down array, shell sort, 2^13 size: " + todownshltime13);
        System.out.println("Operations for sorted to down array, shell sort, 2^13 size: " + todownshloper13);
        System.out.println("Time for simple array, shell sort, 2^13 size: " + simshltime13);
        System.out.println("Operations for simple array, shell sort, 2^13 size: " + simshloper13);


        System.out.println("Time for random array, selection sort, 2^14 size: " + randseltime14);
        System.out.println("Operations for random array, selection sort, 2^14 size: " + randseloper14);
        System.out.println("Time for sorted to up array, selection sort, 2^14 size: " + toupseltime14);
        System.out.println("Operations for sorted to up array, selection sort, 2^14 size: " + toupseloper14);
        System.out.println("Time for sorted to down array, selection sort, 2^14 size: " + todownseltime14);
        System.out.println("Operations for sorted to down array, selection sort, 2^14 size: " + todownseloper14);
        System.out.println("Time for simple array, selection sort, 2^14 size: " + simseltime14);
        System.out.println("Operations for simple array, selection sort, 2^14 size: " + simseloper14);

        System.out.println("Time for random array, insertion sort, 2^14 size: " + randinstime14);
        System.out.println("Operations for random array, insertion sort, 2^14 size: " + randinsoper14);
        System.out.println("Time for sorted to up array, insertion sort, 2^14 size: " + toupinstime14);
        System.out.println("Operations for sorted to up array, insertion sort, 2^14 size: " + toupinsoper14);
        System.out.println("Time for sorted to down array, insertion sort, 2^14 size: " + todowninstime14);
        System.out.println("Operations for sorted to down array, insertion sort, 2^14 size: " + todowninsoper14);
        System.out.println("Time for simple array, insertion sort, 2^14 size: " + siminstime14);
        System.out.println("Operations for simple array, insertion sort, 2^14 size: " + siminsoper14);

        System.out.println("Time for random array, merge sort, 2^14 size: " + randmrgtime14);
        System.out.println("Operations for random array, merge sort, 2^14 size: " + randmrgoper14);
        System.out.println("Time for sorted to up array, merge sort, 2^14 size: " + toupmrgtime14);
        System.out.println("Operations for sorted to up array, merge sort, 2^14 size: " + toupmrgoper14);
        System.out.println("Time for sorted to down array, merge sort, 2^14 size: " + todownmrgtime14);
        System.out.println("Operations for sorted to down array, merge sort, 2^14 size: " + todownmrgoper14);
        System.out.println("Time for simple array, merge sort, 2^14 size: " + simmrgtime14);
        System.out.println("Operations for simple array, merge sort, 2^14 size: " + simmrgoper14);

        System.out.println("Time for random array, shell sort, 2^14 size: " + randshltime14);
        System.out.println("Operations for random array, shell sort, 2^14 size: " + randshloper14);
        System.out.println("Time for sorted to up array, shell sort, 2^14 size: " + toupshltime14);
        System.out.println("Operations for sorted to up array, shell sort, 2^14 size: " + toupshloper14);
        System.out.println("Time for sorted to down array, shell sort, 2^14 size: " + todownshltime14);
        System.out.println("Operations for sorted to down array, shell sort, 2^14 size: " + todownshloper14);
        System.out.println("Time for simple array, shell sort, 2^14 size: " + simshltime14);
        System.out.println("Operations for simple array, shell sort, 2^14 size: " + simshloper14);


        System.out.println("Time for random array, selection sort, 2^15 size: " + randseltime15);
        System.out.println("Operations for random array, selection sort, 2^15 size: " + randseloper15);
        System.out.println("Time for sorted to up array, selection sort, 2^15 size: " + toupseltime15);
        System.out.println("Operations for sorted to up array, selection sort, 2^15 size: " + toupseloper15);
        System.out.println("Time for sorted to down array, selection sort, 2^15 size: " + todownseltime15);
        System.out.println("Operations for sorted to down array, selection sort, 2^15 size: " + todownseloper15);
        System.out.println("Time for simple array, selection sort, 2^15 size: " + simseltime15);
        System.out.println("Operations for simple array, selection sort, 2^15 size: " + simseloper15);

        System.out.println("Time for random array, insertion sort, 2^15 size: " + randinstime15);
        System.out.println("Operations for random array, insertion sort, 2^15 size: " + randinsoper15);
        System.out.println("Time for sorted to up array, insertion sort, 2^15 size: " + toupinstime15);
        System.out.println("Operations for sorted to up array, insertion sort, 2^15 size: " + toupinsoper15);
        System.out.println("Time for sorted to down array, insertion sort, 2^15 size: " + todowninstime15);
        System.out.println("Operations for sorted to down array, insertion sort, 2^15 size: " + todowninsoper15);
        System.out.println("Time for simple array, insertion sort, 2^15 size: " + siminstime15);
        System.out.println("Operations for simple array, insertion sort, 2^15 size: " + siminsoper15);

        System.out.println("Time for random array, merge sort, 2^15 size: " + randmrgtime15);
        System.out.println("Operations for random array, merge sort, 2^15 size: " + randmrgoper15);
        System.out.println("Time for sorted to up array, merge sort, 2^15 size: " + toupmrgtime15);
        System.out.println("Operations for sorted to up array, merge sort, 2^15 size: " + toupmrgoper15);
        System.out.println("Time for sorted to down array, merge sort, 2^15 size: " + todownmrgtime15);
        System.out.println("Operations for sorted to down array, merge sort, 2^15 size: " + todownmrgoper15);
        System.out.println("Time for simple array, merge sort, 2^15 size: " + simmrgtime15);
        System.out.println("Operations for simple array, merge sort, 2^15 size: " + simmrgoper15);

        System.out.println("Time for random array, shell sort, 2^15 size: " + randshltime15);
        System.out.println("Operations for random array, shell sort, 2^15 size: " + randshloper15);
        System.out.println("Time for sorted to up array, shell sort, 2^15 size: " + toupshltime15);
        System.out.println("Operations for sorted to up array, shell sort, 2^15 size: " + toupshloper15);
        System.out.println("Time for sorted to down array, shell sort, 2^15 size: " + todownshltime15);
        System.out.println("Operations for sorted to down array, shell sort, 2^15 size: " + todownshloper15);
        System.out.println("Time for simple array, shell sort, 2^15 size: " + simshltime15);
        System.out.println("Operations for simple array, shell sort, 2^15 size: " + simshloper15);
    }
}
